pygments: true
auto: true
url: http://mdswanson.com
lsi: false
markdown: redcarpet

colors:
  highlight: '#0C84E8'

projects:
  - year: 2013
    projects:
      - name: Stringer
        url: https://github.com/swanson/stringer
        blurb: A self-hosted, anti-social RSS reader

      - name: Hacks && Happenings
        url: http://indyhackers.us6.list-manage.com/subscribe?u=244b5370d41b5cf4146ec517c&id=b51f983563
        blurb: Monthly email newsletter for Indianapolis-area developers

      - name: Triplico
        url: http://www.tripli.co
        blurb: Share YouTube videos among 3 people

      - name: Gem License Checker
        url: http://gemlicensechecker.herokuapp.com
        blurb: Given a Gemfile, determine the license for your dependancies

      - name: Let's Work Happier
        url: http://www.letsworkhappier.com
        blurb: Marketing microsite for MoraleApp, built in an afternoon with Jekyll

  - year: 2012
    projects:
      - name: Morale
        url: https://www.moraleapp.com
        blurb: Daily team mood tracking via email

      - name: QueueRunner
        url: http://www.queuerunner.com
        blurb: Track your TV shows

      - name: ferrara
        url: https://github.com/swanson/ferrara
        blurb: Fetch streaming links (Netflix, Hulu, iTunes) for TV episodes

      - name: Planning Poker
        url: https://github.com/sep/planning-poker-android
        blurb: Android app for conducting agile Planning Poker exercises

      - name: Most Precise Weather
        url: http://mostpreciseweather.com
        blurb: The Most Precise Weather Forecast. Ever. (Accuracy not guarenteed)

      - name: IndyHackers API
        url: http://indyhackersapi.herokuapp.com/events
        blurb: JSON API for the IndyHackers event calendar

      - name: Indy Startup Lab
        url: http://indystartuplab.org
        blurb: Weekly meetup for hackers to work on anything that needs doing

  - year: 2011 
    projects:
      - name: abe
        url: http://abe.heroku.com
        blurb: Abraham Lincoln? Isn't he the President who...

      - name: Netflix It Now
        url: https://github.com/swanson/netflix-it-now
        blurb: Bookmarklet and small webapp to tell me when movies became streamable

      - name: dasher
        url: http://sep.com
        blurb: Company status dashboard, built with Node

      - name: lanyon
        url: https://github.com/swanson/lanyon
        blurb: WYSIWYG editor for Jekyll powered blogs, hooked directly into the Github API

      - name: CloutBout
        url: https://github.com/swanson/cloutbout
        blurb: Fantasy sports for Twitter, built in under 36 hours for SDC Chicago 2011 Hackathon

      - name: WhooWho!
        url: http://www.sep.com/labs/event0711.html
        blurb: Lean CRM with recommendations, built at SEP Startup Weekend Summer 2011

      - name: bibliotechnical
        url: https://github.com/swanson/bibliotechnical
        blurb: Programming book recommendation site

      - name: LandingPad.rb
        url: http://github.com/swanson/LandingPad.rb
        blurb: Landing page app, deployed on Heroku using Sinatra + MongoDB

  - year: 2010
    projects:
      - name: Glorified Screensaver
        url: http://github.com/swanson/glorified-screensaver
        blurb: Real-time announcement board built with Node.js, socket.io, and three.js

      - name: StackTracker
        url: http://github.com/swanson/stacktracker
        blurb: Cross-platform desktop notifier for the StackExchange API

      - name: Duel of Tweets
        url: http://github.com/swanson/duel-of-tweets
        blurb: Head-to-head polls conducted over Twitter, built in under 36 hours for SDC Chicago 2010 Hackathon

      - name: flask-embedly
        url: http://github.com/swanson/flask-embedly
        blurb: Flask extension that adds Embedly support to templating

      - name: autocastr
        url: http://github.com/swanson/autocastr
        blurb: Automatically download and partition podcasts into CD-R sized folders

      - name: Mongo Overflow
        url: http://github.com/swanson/mongo-overflow
        blurb: Small StackOverflow clone with a mongoDB backend

      - name: Bumps
        url: http://github.com/swanson/bumps
        blurb: OBD-II iPhone logging application and server, used for pothole detection research